### ISSUE TITLE
The prompt does not initiate installation of .net.  Installing .net manually does not prevent the prompt or allow the executable to run.

### ISSUE THREAD

**Issue by Lurkily** [Museus/HadesSaveManager#2]
Clicking "Yes" when prompted "would you like to download it now results in the dialog box disappearing. Nothing further appears to happen.

**Comment by Museus** [comment]
I believe this is an issue with me using a non-standard .NET framework. I'm not sure why, but some people have issues getting windows to recognize the version they need.

I'm going to make a branch that targets 6.0 instead of Core 3.1, and see if that will solve the issue.

**Comment by Museus** [comment]
https://github.com/Museus/HadesSaveManager/releases/tag/v1.3.0-rc.1

Here is a release candidate that was built with .NET 6.0 as the target framework. Let me know if it works for you.

**Comment by shaheerszm** [comment]
> 

it worked for me, thanks

**Comment by Museus** [comment]
This was resolved by [release v1.3.0](https://github.com/Museus/HadesSaveManager/releases/tag/v1.3.0)
